import numpy as np
marks = np.array([45, 88, 72, 95, 30, 67, 81, 55, 92, 39])
print("...... STUDENT REPORT ......")
print("All marks:")
print(marks)
print("\nTotal students:")
print(marks.size)
print("\nAverage marks:")
print(marks.mean())
print("\nHighest marks:")
print(marks.max())
print("\nlowest marks:")
print(marks.min())
print("\nPassed students:")
print(marks[marks >= 40])
print("\nFailed students:")
print(marks[marks < 40])
print("\nTop students (> 80):")
print(marks[marks > 80])
print("\nA Garde students (>90):")
print(marks[marks >90])
print("\nClass percentage:")
print((marks.mean()/100)*100)
print("\nNumber of passed students:")
print((marks >= 40).sum())
print("\nNumber of failed students:")
print((marks < 40).sum())